<div id="project-list">
	<h5>
		Your projects
		<button class="btn btn-sm btn-primary right" id="add-new-list">
			<i class="fa fa-plus"></i>
		</button>
	</h5>
	<div>
		<ul>

		</ul>
	</div>
</div>

<div id="tasks-list">
	
	<div class="add-task-form">
		<input type="text" class="form-control" id="new-task-body" placeholder="What is your task? Write it here"/>
	</div>
	<button class="btn btn-success" id="add-task">Add new task</button>
	<div class="clearfix cfx10"></div>
	<h4>Tasks list:</h4>
	<ul>
		
	</ul>
</div>
